# SPDX-FileCopyrightText: 2023 Lennart Heimbs <lennart@heimbs.me>
#
# SPDX-License-Identifier: MIT

---
name: Build and Test

on: pull_request

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
        working-directory: "pitmutationmate"

      - name: Run Tests
        run: ./gradlew test --no-daemon
        working-directory: "pitmutationmate"

      # Run Qodana inspections
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2023.2.8
        with:
          cache-default-branch-only: true

      - name: Run Plugin Verification tasks
        run: ./gradlew runPluginVerifier --no-daemon
        working-directory: "pitmutationmate"
